import { css } from 'react-strict-dom';
import { tokens } from '../../theme/tokens.css';

export const styles = css.create({
  rightSlotContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing8,
  },
  divider: {
    width: 1,
    height: tokens.spacing12,
    backgroundColor: tokens.colorBorderSecondary,
  },
  eyeButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: tokens.spacing24,
    height: tokens.spacing24,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: tokens.spacing6,
    padding: 0,
    cursor: 'pointer',
  },
  inputWrapper: {
    position: 'relative',
    zIndex: 1,
  },
  infoBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing8,
    backgroundColor: tokens.colorSurfaceHover,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.colorBorderSecondary,
    borderTopWidth: 0,
    borderBottomLeftRadius: tokens.radius8,
    borderBottomRightRadius: tokens.radius8,
    paddingTop: tokens.spacing12,
    paddingBottom: tokens.spacing12,
    paddingLeft: tokens.spacing12,
    paddingRight: tokens.spacing12,
    position: 'relative',
    zIndex: -1,
  },
  infoBoxIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  infoBoxText: {
    flex: 1,
    flexShrink: 1,
    color: tokens.colorTextPrimary,
    fontFamily: tokens.fontPrimary,
    fontSize: tokens.fontSize12,
    fontWeight: tokens.weightRegular,
    lineHeight: 'normal',
  },
});
